### ISSUE TITLE
Anisotropic downsampling doesn't work as expected

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#337]
I was trying  to downsample a dataset with scale 11.24,11.24,28. By default it will create 1, 2-2-1, 4-4-1, 8-8-2, ...
However, I want something like 1, 2-2-1, 4-4-2, 8-8-4, ...

Earlier, I was able to do that with `--anisotropic_target_mag 512-512-256`. That flag seems to be deprecated. The error message says, I should be using  `target_mag` which is not a valid arg. https://github.com/scalableminds/webknossos-cuber/blob/master/wkcuber/downsampling.py#L135-L138

Btw, my understanding of "deprecated" is that a functionality is not encouraged anymore, but still works now, and will be removed later.

**Comment by rschwanhold** [comment]
In this PR (https://github.com/scalableminds/webknossos-cuber/pull/304), the downsampling interface was redesigned to make it more intuitive. Previously there were different methods for downsampling anisotropic or isotropic. As a result the flag `--anisotropic_target_mag` was removed. As you pointed out, the error message is wrong: it should say `--max` instead of `--target_mag`. 
However, using `--max` is not enough for your use case (see below). 

The design of the new interface was use-case oriented. In the process three major use-cases were identified, which resulted in the following `SamplingModes`:
- 'auto' - The next magnification is chosen so that the width, height and depth of a downsampled voxel assimilate. For example, if the z resolution is worse than the x/y resolution, z won't be downsampled in the first downsampling step(s). As a basis for this method, the scale from the datasource-properties.json is used.
- 'isotropic' - Each dimension is downsampled equally.
- 'constant_z' - The x and y dimensions are downsampled equally, but the z dimension remains the same.

The need for a mode where the scale is calculated based on the `max_mag` was unintentionally neglected.

I suggest that we add another sampling mode called `anisotropic`. Your could then set `--max` to `512-512-256` and `--sampling_mode` to `anisotropic`.

I am just wondering what the behavior would be if `--sampling_mode` is set to `anisotropic`, but `--max` is not set.

**Comment by normanrz** [comment]
Regarding the sampling modes, I would think that `auto` would be one of the other modes chosen automatically and not be an own mode byitself. Does that make sense? With that, `anisotropic` would use the `--max` if available or derive the downsampling scheme from the scale (as is).

**Comment by rschwanhold** [comment]
After giving this another thought:
Are you simply unsatisfied with the downsampling scheme that is calculated when using `11.24,11.24,28` (and are trying to find a way around it) or is there a real use case to use a (completely) different scale to downsample an anisotropic dataset? 

Currently the method `get_next_mag` is used to calculate the next magnification. 
```
get_next_mag(mag=Mag([2, 2, 1]), scale=(10, 10, 20)).to_layer_name()  # 4-4-2
get_next_mag(mag=Mag([2, 2, 1]), scale=(9.9, 9.9, 20)).to_layer_name()  # 4-4-1
```
If you were expecting a different downsampling scheme, maybe the best solution would be to change `get_next_mag` .

**Comment by normanrz** [comment]
Good question. In my case I had an existing `color` layer and wanted to add layers that match the downsampling. But you are right, in the case you've shown the better downsampling would be `4-4-2`, I think.

**Comment by rschwanhold** [comment]
Then I will adjust `get_next_mag`; fix the error message; and rename the mode `auto` to `anisotropic` (which will be default).

**Comment by hotzenklotz** [comment]
As a workaround I was able to cheat the system by using `--from_mag` argument get the desired 1-1-1, 2-2-1, 4-4-2, 8-8-4... mags. In a second downsampling run I did: 

```
python -m wkcuber.downsampling  --from_mag 2-2-1 --max 1024 --sampling_mode isotropic <path>
```

**Comment by rschwanhold** [comment]
I would like to get some feedback to the downsampling scheme. 
Here are some examples with a given `scale`, `from_mag` and `max_mag`. I would like to know if the resulting magnifications are correct/expected.
If there are any cases that I have missed, please let me know.

```
# --- Anisotropic --- 
scale=(10.5, 10.5, 24)
from_mag=(1, 1, 1), 
max_mag=(16, 16, 8)
downsampled magnifications: [(2, 2, 1), (4, 4, 2), (8, 8, 4), (16, 16, 8)]),

scale=(10.5, 10.5, 24)
from_mag=(1, 1, 1)
max_mag=(16, 16, 16)
downsampled magnifications: [(2, 2, 1), (4, 4, 2), (8, 8, 4), (16, 16, 8), (16, 16, 16)]),

scale=(10.5, 10.5, 24)
from_mag=(1, 1, 1)
max_mag=(8, 8, 16)
downsampled magnifications: [(2, 2, 1), (4, 4, 2), (8, 8, 4), (8, 8, 8), (8, 8, 16)]),

scale=(10.5, 10.5, 10.5)
from_mag=(1, 1, 1)
max_mag=(16, 16, 16)
downsampled magnifications: [(2, 2, 2), (4, 4, 4), (8, 8, 8), (16, 16, 16)]),

scale=(10.5, 10.5, 10.5)
from_mag=(1, 1, 1),
max_mag=(8, 8, 16)
downsampled magnifications: [(2, 2, 2), (4, 4, 4), (8, 8, 8), (8, 8, 16)]),

scale=(1, 1, 2)
from_mag=(2, 2, 1)
max_mag=(16, 16, 8)
downsampled magnifications:  [(4, 4, 2), (8, 8, 4), (16, 16, 8)]),

scale=(1, 1, 2)
from_mag=(2, 2, 2)
max_mag=(16, 16, 8)
downsampled magnifications: [(4, 4, 2), (8, 8, 4), (16, 16, 8)]),

scale=(1, 1, 4)
from_mag=(1, 1, 1)
max_mag=(16, 16, 2)
downsampled magnifications: [(2, 2, 1), (4, 4, 1), (8, 8, 2), (16, 16, 2)]),

# --- Constant Z --- 
scale=(1, 1, 2)
from_mag=(1, 1, 1)
max_mag=(16, 16, 1)
downsampled magnifications: [(2, 2, 1), (4, 4, 1), (8, 8, 1), (16, 16, 1)]),

# --- Isotropic --- 
scale=None
from_mag=(1, 1, 1), 
max_mag=(8, 8, 8)
downsampled magnifications: [(2, 2, 2), (4, 4, 4), (8, 8, 8)]),

scale=None
from_mag=(1, 1, 1), 
max_mag=(16, 16, 8)
downsampled magnifications: [(2, 2, 2), (4, 4, 4), (8, 8, 8), (16, 16, 8)]),

scale=None
from_mag=(2, 2, 1)
max_mag=(8, 8, 4) 
downsampled magnifications: [(4, 4, 2), (8, 8, 4)]),

scale=None
from_mag=(2, 2, 1)
max_mag=(8, 8, 8)
downsampled magnifications: [(4, 4, 2), (8, 8, 4), (8, 8, 8)]),
```

(The upsampling scheme is analog)

**Comment by normanrz** [comment]
How do you now decide what mag to pick? What happens with `max_mag=None`?

I think these 2 are not supported by webKnossos, because max(x,y,z) needs to be unique:
```
scale=(10.5, 10.5, 24)
from_mag=(1, 1, 1)
max_mag=(16, 16, 16)
downsampled magnifications: [(2, 2, 1), (4, 4, 2), (8, 8, 4), (16, 16, 8), (16, 16, 16)]),

scale=(10.5, 10.5, 24)
from_mag=(1, 1, 1)
max_mag=(8, 8, 16)
downsampled magnifications: [(2, 2, 1), (4, 4, 2), (8, 8, 4), (8, 8, 8), (8, 8, 16)]),
```

Not sure about this one:
```
scale=(10.5, 10.5, 10.5)
from_mag=(1, 1, 1),
max_mag=(8, 8, 16)
downsampled magnifications: [(2, 2, 2), (4, 4, 4), (8, 8, 8), (8, 8, 16)]),
```

Examples of what I would expect:
```
scale=(10.5, 10.5, 24)
from_mag=(1, 1, 1), 
max_mag=None
downsampled magnifications: [(2, 2, 1), (4, 4, 2), (8, 8, 4), (16, 16, 8)]),

scale=(10.5, 10.5, 35)
from_mag=(1, 1, 1), 
max_mag=None
downsampled magnifications: [(2, 2, 1), (4, 4, 1), (8, 8, 2), (16, 16, 4)]),
```

**Comment by rschwanhold** [comment]
> How do you now decide what mag to pick? What happens with `max_mag=None`?

If the user specifies a max mag (e.g. with `--max` from the command line), then this mag is used. Otherwise the default max mag is calculated. If the mode `CONSTANT_Z` is used, the z-value of the `max_mag` is set to the z-value of the `from_mag`. Therefore `max_mag=None` never happens.

For the calculation see https://github.com/scalableminds/webknossos-cuber/pull/391/files#diff-192fd4f081bc450297dbcc1739e207ad620d667b680cee012096eea87fc1c8a3R39.
