### ISSUE TITLE
Add symlinking for mags

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#363]
There is already a function that allows symlinking of full layers. However, sometimes it is useful to only symlink some mags. A typical use case is to create a "downsampled" version of the dataset, e.g. where mag 8 becomes mag 1. The reason to do this is to be able to create volume annotations of large features, such as nuclei.

```
downsampled_dataset
  - color
    - 1 -> ../../original_dataset/color/8
    - 2 -> ../../original_dataset/color/16
    - 4 -> ../../original_dataset/color/32
    - 8 -> ../../original_dataset/color/64
    - 16 -> ../../original_dataset/color/128
  
```

**Comment by rschwanhold** [comment]
Implementing a function to add a magnification with symlinks should be easy. Renaming the magnifications could either be done with an optional parameter to `add_symlink_mag` or an explicit function `MagView.rename(...)` (what do you prefer)? However, in both cases, this has consequences because the name of the mag is used to calculate the size of the  bounding box in the current mag.
Example:
Bounding box size in Mag `1`: `1024, 1024, 1024` (this is stored in the properties)
Bounding box size in Mag `2`: `512, 512, 512`

If one would now rename the mag `2` to `4`, then the `MagView` of `4` would be limited to `256, 256, 256`! (or should the bounding box of mag `1` be scaled to `2048, 2048, 2048`?)

**Comment by normanrz** [comment]
I think the main use case, I had in mind was creating a new layer and then adding the symlinked mags.

**Comment by normanrz** [comment]
Maybe we could also offer a convenience function for the use case I described.

**Comment by fm3** [comment]
@normanrz To be honest, aliasing mags like this seems like a large source of confusion to me. Would this still be needed if https://github.com/scalableminds/webknossos/issues/5642 would be solved?

**Comment by normanrz** [comment]
It would probably not be required anymore. Another use case that I can think of is to re-use the mag 1 and apply a different downsampling than in the original dataset. But I don't think we actually had that before.

I don't think that aliasing would be a large source of confusion. We have been working with this for quite some time.
