### ISSUE TITLE
Add `executor` arg to downsample, compress etc

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#370]
In some scripts, there is already an executor object available. It would be good to be able to pass it directly to processing functions, such as downsample, compress etc.

**Comment by rschwanhold** [comment]
I have implemented this, but there might be a conceptual problem. I renamed the parameter `args` to `executor_args` (of type `Optional[Union[ClusterExecutor, WrappedProcessPoolExecutor, Namespace]]`). However, if I understand it correctly, an executor can only be used once. This causes problems.

Consider the following example, which does not work because the same executor is used multiple times: 
```
    ds = Dataset.create(Path(tmp_path), scale=(2, 2, 1))
    layer = ds.add_layer("color", LayerCategories.COLOR_TYPE)
    mag = layer.add_mag("1", file_len=8, block_len=8)

    original_data = (np.random.rand(50, 100, 150) * 205).astype(np.uint8)
    mag.write(offset=(70, 80, 90), data=original_data)

    with get_executor_for_args(None) as executor:
        layer.downsample_mag(Mag(1), Mag(4), executor_args=executor)
        mag.compress(executor_args=executor)  # <-- fails
        layer.get_mag(Mag(2)).compress(executor_args=executor)
        layer.get_mag(Mag(4)).compress(executor_args=executor)

    assert set(layer.mags.keys()) == {Mag(1), Mag(2), Mag(4)}
```

The downsampling works, but the first compress-call fails with the following error message `RuntimeError: cannot schedule new futures after shutdown`

An even more obvious example would be `layer.downsample(Mag(1), Mag(4), executor_args=executor)` because each downsample step uses an executor.

Do you explicitly want to execute the method with your already existing executor? 
Or is your motivation that you only have an existing executor (instead of the args) and passing the executor would be convenient for you? 
If the later is the case, then the best solution might be to infer the args from the existing executor automatically and then create a new executor. The passed executor would then only act as a blueprint.

**Comment by normanrz** [comment]
> Or is your motivation that you only have an existing executor (instead of the args) and passing the executor would be convenient for you?

My initial problem was that I don't know how to trigger slurm distribution with the Dataset-API. It seems inconvenient to create a `Namespace` and pass args, whereas creating an `ClusterExecutor` is straight-forward.
 
> If the later is the case, then the best solution might be to infer the args from the existing executor automatically and then create a new executor. The passed executor would then only act as a blueprint.

Maybe there could be a `.clone()` or `.reset()` method on the executor to be re-used.
