### ISSUE TITLE
method naming: `as_np` vs `to_array`

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-libs#407]
Those are functions in the `Mag` class. Should for consistency possibly also be `as_array`? Also, should it be `as_list` instead, since the method returns a python list?
There is also other methods with `to`, e.g. `to_layer_name`.
What are your thoughts on this?

**Comment by jstriebel** [comment]
Yes, please! On that note we should also double-check the bounding-box methods. 

My thoughts so far:
* the conversions return lists should be called `to/as_list`, not `array`
* Using `to`/`as` should be consistent. Some arguments:
  * In my opinion `to` sounds more like a conversion (e.g. where some computation is necessary, and the data might change slightly). But no strong opinion here.
  * The pythonic way seems to be to use the constructors mostly, e.g. `str(3)`, `int("-4")`, …. I still find the `to`/`as` methods quite useful, since they are discoverable, don't need yet another import, and are the only way to provide converters for already existing classes (e.g. np.ndarray).
  * numpy has `np.ndarray.tolist` and `np.asarray` :see_no_evil: 
  * pandas has `pd.DataFrame.to_numpy`
  * I personally don't care which one we use :man_shrugging:, just about constistency.

**Comment by fm3** [comment]
Looks like there may be some arguments for having both as and to in one codebase …
https://softwareengineering.stackexchange.com/questions/352157/whats-the-difference-between-to-and-as-method-name-prefixes (this is mostly about java/c++ though)
I’m unsure about the best way

**Comment by jstriebel** [comment]
Other topics that need some thought (we might want to spread this into separate issues/PRs)
* avoid mutability of properties
* avoid that objects returned by `to`/`as` mutate its origin
* should we have a Vec3 class? (Vec3i / Vec3f)
* from_auto vs constructor
* BoundingBoxNamedTuple is superfluous, serialization should be done externally (helpers might exist, though)
* should Mag / BoundingBox / Vec be a NamedTuple (or dataclass/attrs/pydantic/…)

PS: Probably all converters should be called `to` and return a copy.
