### ISSUE TITLE
Allow to symlink existing public dataset layers when uploading dataset

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-libs#509]
The webKnossos server API now ( https://github.com/scalableminds/webknossos/pull/5863 ) allows to symlink existing public dataset layers into an uploaded dataset. The client should be able to use this field and expose it to a user.

**Comment by philippotto** [comment]
I'm not sure what exactly this should look like. From a user perspective, I would probably imagine an interface like this:

```python
ds = download_dataset(dataset_name, organization_name)
existing_layer = ds.get_layer("existing_layer", ...)
new_layer = ds.add_layer("new_layer", ...)
foreign_layer = ds.add_symlink_layer(foreign_layer_descriptor)

ds.upload()
```

However, it's not clear to me how the `upload` method would know which layer to symlink. For example, for the `existing_layer` one would need to know whether the user has mutated the layer or whether it's equivalent to the server side.

An explicit approach would be to require the user to pass the necessary information. Potentially:

```python
ds.upload(layers_to_symlink=["existing_layer"])
```

Or, even more information:

```python
ds.upload(layers_to_symlink=[
      {
        organizationName: "...",
        dataSetName: "...",
        layerName: "foreign_layer",
        newLayerName: "foreign_layer"
      }
])
```

which already feels quite complicated.

-----------------

For the (probably simpler) usecase, where I'm creating a fresh dataset on disk, I'm not even sure whether it's realistic to symlink something on the server (why would I create a brand-new DS in the first place which matches existing data?).

------------

All in all, I'm not yet seeing the big picture here. I hope you can help me with getting the details straight. I'm happy to implement a basic version which works somehow, but I'm not sure if this solves a use case satisfactorily.

Happy to hear your thoughts! (also cc @jstriebel)

**Comment by fm3** [comment]
CCing @normanrz who brought up this feature request and may have more insights about the desired use case

**Comment by normanrz** [comment]
I think this is what I was imagining:
```python
ds.upload(layers_to_link=[
      {
        organizationName: "...",
        dataSetName: "...",
        layerName: "foreign_layer",
        newLayerName: "foreign_layer"
      }
])
```

`organizationName` and `newLayerName` should be optional.

The primary use case for this feature is to upload new layers (e.g. a segmentation) to an existing dataset, without modifying the original.

Nit: I wouldn't call it `symlink`, because that is an implementation detail on the server-side.

**Comment by jstriebel** [comment]
I think @normanrz's proposal looks good. How does it work, if a layer_to_link is already part of the ds to upload? I guess it is simply skipped then, or should this be forbidden? And maybe we want to type the layers_to_link argument with a simple namedtuple (anyhow using snake_case), e.g.
```
ds.upload(layers_to_link=[
      LayerToLink(
        organization_name="...",  # Optional[str] with default None
        dataset_name="...",
        layer_name="foreign_layer",
        new_layer_name="my_linked_foreign_layer"  # Optional[str] with default None
      )
])
```

PS: I think we should settle on Dataset and dataset instead of dataSet or sth similar^^

**Comment by philippotto** [comment]
> How does it work, if a layer_to_link is already part of the ds to upload? I guess it is simply skipped then, or should this be forbidden?

I think, the layer shouldn't be uploaded (but linked) then. This is probably the default case, though, if I'm understanding it correctly (so, it should not be forbidden).

> And maybe we want to type the layers_to_link argument with a simple namedtuple (anyhow using snake_case), e.g.

> PS: I think we should settle on Dataset and dataset instead of dataSet or sth similar^^

:+1: to both.

------------

I'll implement the discussed version. However, I'm seeing it rather as a low-level building block. In my opinion, the described use case ("The primary use case for this feature is to upload new layers (e.g. a segmentation) to an existing dataset, without modifying the original.") can be better handled, if a downloaded dataset "knows" from where it was downloaded. Then, all necessary metadata are available so that an interface like `ds.upload(layers_to_symlink=["existing_layer"])` also works.
