### ISSUE TITLE
[Question] wkcuber: creating compressed datasets on the fly

### ISSUE THREAD

**Issue by neuronflow** [scalableminds/webknossos-libs#847]
I am trying to create a visualization of several 200 GB 3D microscopy scans. I am prototyping with a toy dataset.

I am creating the cubes with:
```
python -m wkcuber.convert_nifti --verbose --compress --layer_name color --voxel_size  10,10,10 data/mr_example_data/t1.nii.gz data/t1_cubes
```

Even though the compressed niftis is 15MB, the  resulting cubes folder has 1.1GB.

Should I expect a similar size gain for the 200gb dataset so 200gb * 73 ~ 14.6TB per scan?
-> I would need a server with over 100TB to host this?!

I then tried to compress the data with:
```
# Compress data copy (mostly useful for segmentation)
python -m wkcuber.compress --layer_name color data/t1_cubes data/t1_cubes_compressed
```
Even though it says  `mostly useful for segmentation` in the documentation. This reduces the size to 12MB!
Is there an option to do this directly, so no 14.6TB dataset would have to be saved?

Do the other converter e.g. from tiff provide compression options?

**Comment by normanrz** [comment]
Hi @neuronflow, thanks for trying out webKnossos!

webKnossos organizes its data in chunk files with 1024x1024x1024 voxel. That means for 8-bit data, the uncompressed file size is 1GB. Even if you convert small data (like your 15MB file), it will produce WKW files with at least 1GB. Compression helps a lot here, because it can essentially eliminate the empty parts of the file. However, if you have an input file of ~200GB I would expect an output size of ~200GB (even uncompressed), because the overhead is amortized with data size.

`wkcuber.convert_nifti` can convert the data into uncompressed WKW, which can then we compressed in-place with `python -m wkcuber.compress /path/to/data`.
Adding direct compression would be possible, especially for small files that fit in RAM (twice).

**Comment by neuronflow** [comment]
I see, so I cannot extrapolate space requirements based on my toy dataset. thanks! :)
